name: check

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Moon (nightly)
        uses: moonbit-community/setup-moonbit@main
        with:
          version: nightly

      - name: moon version
        run: moon version --all

      - name: install module dependencies
        run: moon update

      - name: moon check
        run: moon check --deny-warn --target native --warn-list=-ambiguous_braces-lexmatch_longest_match

      - name: moon build
        run: |
          moon build --target native
          moon build --target wasm

      - name: moon info
        run: |
          moon info --target native
          git diff --exit-code

      - name: format diff
        run: |
          moon fmt
          git diff --exit-code

      - name: Set ulimit
        run: ulimit -s 8176

      - name: moon test
        run: |
          moon test --target native
          moon test --target native

      - name: moon test (wasm)
        run: moon test --target wasm
